[package]
name = "aquinas"
version = "0.0.9"
license = "MPL-2.0"
readme = "README.md"
description = "A simple command line media player. (Like cmus, but simpler.)"
categories = ["multimedia", "multimedia::audio"]
keywords = ["audio", "multimedia", "media", "mediaplayer"]
authors = ["Dakota Brink <git@kota.is>"]
repository = "https://github.com/codabrink/aquinas"
edition = "2021"

[dependencies]
anyhow = "1"
dirs = "4"
tui = "0.18"
crossterm = "0.23"
crossbeam-channel = "0.5"
hashbrown = "0.12"
tokio = { version = "1.17", features = ["full"] }
parking_lot = "0.12"
toml = "0.5"
serde = "1"
serde_derive = "1"

gstreamer = { version = "0.18", optional = true }
gstreamer-player = { version = "0.18", optional = true }
gstreamer-pbutils = { version = "0.18", optional = true }

rodio = { version = "0.15", optional = true }

# mp3, flac
audiotags = "0.2"
# mp3
mp3-duration = { version = "0.1", optional = true }
# opus
opus_headers = "0.1"
# ogg
lewton = "0.10"
ogg_metadata = { version = "0.4.1", optional = true }

[features]
default = ["gstreamer_backend"]
gstreamer_backend = ["gstreamer", "gstreamer-player", "gstreamer-pbutils"]
rodio_backend = ["rodio", "mp3-duration", "ogg_metadata"]

[profile.release]
strip = true
lto = true
