[package]
name = "aquinas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
gstreamer = "0.17"
gstreamer-player = "0.17"
gstreamer-pbutils = "0.17"
termion = "1.5"
tui = "0.16"
crossbeam-channel = "0.5"