[package]
name = "aquinas"
version = "0.1.0"
authors = ["Dakota Brink <aquinas@dakota.io>"]
edition = "2021"

[dependencies]
anyhow = "1"
dirs = "4"
gstreamer = "0.17"
gstreamer-player = "0.17"
gstreamer-pbutils = "0.17"
termion = "1.5"
tui = "0.16"
crossbeam-channel = "0.5"
hashbrown = "0.11"
