[package]
name = "aquinas"
version = "0.1.0"
authors = ["Dakota Brink <aquinas@dakota.io>"]
edition = "2021"

[dependencies]
anyhow = "1"
dirs = "4"
gstreamer = "0.18"
gstreamer-player = "0.18"
gstreamer-pbutils = "0.18"
termion = "1.5"
tui = "0.17"
crossbeam-channel = "0.5"
hashbrown = "0.12"

# mp3, flac
audiotags = "0.2"
# opus
opus_headers = "0.1"
# ogg
lewton = "0.10"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "aquinas_benches"
harness = false
